project:
  type: website
  output-dir: docs


website: 
  title: "Van Stewart's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About Me"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

