---
title: "DataPrep"
author: "Van Stewart"
editor: visual
---

```{r}
#|label: Packages!

library(tidyverse)
```

```{r}
#|label: DataLoading



## install.packages("tidytuesdayR")

tuesdata <- tidytuesdayR::tt_load('2024-05-21')
## OR
tuesdata <- tidytuesdayR::tt_load(2024, week = 21)

emissions <- tuesdata$emissions




```

```{r}
#|label: Colors!


colorsVanLikes <- c(
  "dodgerblue2", 
  "#E31A1C", 
  "green4",
  "#6A3D9A", 
  "skyblue2", 
  "#FB9A99", 
  "#CAB2D6",
  "#FDBF6F", 
  "maroon", 
  "orchid1", 
  "deeppink1", 
  "blue1",
  "steelblue4",
  "darkturquoise", 
  "green1", 
  "darkorange4",
  "brown",
  "cyan",
  "cyan4",
  "coral",
  "darkgreen",
  "blue",
  "red4",
  "green4"
)
```

```{r}
#|label: DataCleaning


emissionsCleanParent <- emissions |>
  filter( commodity == "Oil & NGL",
          year >= 1970
          )|>
  select( -c( parent_type, 
              production_value, 
              production_unit
              ))|>
 mutate(total_emissions_MtCO2e = as.numeric(total_emissions_MtCO2e)) |>
  group_by(parent_entity)|>
  mutate(avg_emissions = mean(total_emissions_MtCO2e))|>
  filter( avg_emissions >= 300)|>
  ungroup()#|>
  #write.csv('Data-clean/emissionsCleanParent.csv')

emissionsCleanCommodity <- emissions |>
  filter( year >= 1970
          )|>
  select( -c( parent_type, 
              production_value, 
              production_unit
              ))|>
  mutate(total = as.numeric(total_emissions_MtCO2e)) |>
  group_by(year, commodity)|>
  mutate(avg_emissions = mean(total_emissions_MtCO2e))|>
  filter( avg_emissions >= 0)|>
  ungroup()#|>
  #write.csv('Data-clean/emissionsCleanCommodity.csv')
```

```{r}
#|label: Graphics



emissionsCleanParent|>
  ggplot( aes( x = year,
               y = total_emissions_MtCO2e,
               group = parent_entity,
               color = parent_entity
               ))+
  theme_minimal()+
  scale_color_manual(values = colorsVanLikes)+
  geom_line()

emissionsCleanCommodity|>
  ggplot( aes( x = year,
               y = avg_emissions,
               group = commodity,
               color = commodity
               ))+
  theme_minimal()+
  scale_color_manual(values = colorsVanLikes)+
  geom_line()
```
